const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../web/app.js'), 'utf8');
const start = source.indexOf('function rolloutWorkloadHtml(');
const end = source.indexOf('function bindEnvForm()', start);
const context = vm.createContext({ esc: (s) => String(s ?? '') });
vm.runInContext(source.slice(start, end), context);
const panel = { dataset: {}, innerHTML: '', querySelectorAll: () => [] };
const base = { id: 'release2', old: {exists:true}, new:{exists:true}, can_rollback:true };
context.renderEnvRollouts(panel, [{...base, status:'superseded', can_manage:false}], '', 'release');
assert.match(panel.innerHTML, /已完成 · 已由历史回滚结束/);
assert.doesNotMatch(panel.innerHTML, /data-rollout-offline|data-rollout-scale/);
context.renderEnvRollouts(panel, [{...base, status:'superseded', can_manage:false}], '', 'rollback');
assert.match(panel.innerHTML, /data-rollout-rollback/);
context.renderEnvRollouts(panel, [{...base, status:'rolled_back', can_manage:false}], '', 'rollback');
assert.match(panel.innerHTML, /disabled aria-disabled="true" title="本次发布已经回滚">一键回滚/);
assert.doesNotMatch(panel.innerHTML, /data-rollout-rollback/);
context.renderEnvRollouts(panel, [{...base, status:'active', can_manage:true}], '', 'release');
assert.match(panel.innerHTML, /data-rollout-offline/);
assert.match(panel.innerHTML, /data-rollout-scale/);
context.renderEnvRollouts(panel, [{...base, can_rollback:false}], '', 'rollback');
assert.doesNotMatch(panel.innerHTML, /历史版本缺少恢复快照/);
assert.doesNotMatch(panel.innerHTML, /data-rollout-rollback/);
console.log('Rollback UI states: passed');
